name: Validate Pull Request

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title and body
        id: check_pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;

            const title = pr.title || "";
            const body = pr.body || "";
            const labels = pr.labels.map(l => l.name);

            let errors = [];

            // 1. Check title rule
            if (!/^(feature|fix|chore|docs):/i.test(title)) {
              errors.push("❌ PR title must start with 'feature:', 'fix:', 'chore:', or 'docs:'.");
            }

            // 2. Check body rule
            if (body.length < 10) {
              errors.push("❌ PR description must be at least 10 characters long.");
            }

            // 3. Check label presence
            if (labels.length === 0) {
              errors.push("❌ PR must have at least one label.");
            }

            // If any errors, post a comment and fail
            if (errors.length > 0) {
              const message = errors.join("\n");
              await github.rest.issues.createComment({
                issue_number: pr.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
              core.setFailed(message);
            } else {
              console.log("✅ PR looks good!");
            }
